### ISSUE TITLE
Conflicting whitespace rules for : operator and line continuation

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#108]
**MISS_HIT Component affected**
Please choose one from:
* Style checker

**Your operating system and Python version**
* Linux
* State output of `python3 --version`
Python 3.6.9

**Describe the bug**
Conflicting rules when using the `:` operator combined with line continuation
In this example the whitespace continuation rule complains about lack of space before `...`:
```
for i = 1:...
    10
```
If the whitespace is added before `...` it is automatically removed because of the rule that says that colon should not be followed by whitespace.

Please add an exception for the "no whitespace after colon" rule if the colon is followed by `...`

**Comment by florianschanda** [comment]
Should have been fixed in #100 but maybe something doesn't work yet...
