### ISSUE TITLE
relax copyright location

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#121]
**What kind of feature is this?**
* New feature in MISS_HIT

**MISS_HIT component affected**
Choose one or more of the below:
* Style checker

**Describe the solution you'd like**
Having the copyright statement before the function declaration breaks the `help` and `doc` features in matlab. They only show the copyright statement and not the function help. The only workaround is to also put the function help comment before the function declaration which is not the convention for matlab code.

**Comment by florianschanda** [comment]
I propose to update the rule to allow two places the copyright can be found:
1. As the very first comment in a file (as it is right now)
2. As the first comment in the first function/class body

**Comment by Remi-Gau** [comment]
In relation with #203 for `Contents.m` files.

I learned through that other issue that Matlab can generate the Contents.m file automatically by using the first nonempty comment **line**

> The new file includes the names of all program files in the folder, using the description line (the first nonempty comment line) whenever it is available.

I suspect that either options described above for the Copyright would break that functionality and results only in a list of Copyrights in `Contents.m`.

So maybe having the copyright as a last non-empty comment line in the description section, might work better ?

**Comment by florianschanda** [comment]
I will make this configurable, with a copyright_location style config, which can be set to (initially):
* `file_header` (the current behaviour)
* `in_docstrings` (somewhere in the docstring for the script or the primary entity (function/file))

**Comment by Remi-Gau** [comment]
once gain: thanks for doing all this!!! You're a :star:

**Comment by florianschanda** [comment]
@Remi-Gau could I possibly ask you to test the current `master` branch? I've implemented this but since I am in holiday I don't really have access to my work's MATLAB code base.

I am reasonably sure it should work, but a sanity check might be helpful before I release something :)

I am taking the bold step to change the default behaviour (so no new configuration should be necessary).

**Comment by Remi-Gau** [comment]
> @Remi-Gau could I possibly ask you to test the current `master` branch? I've implemented this but since I am in holiday I don't really have access to my work's MATLAB code base.

Will give it a go. Definitely try to enjoy your holidays!!!

> I am reasonably sure it should work, but a sanity check might be helpful before I release something :)
> 
> I am taking the bold step to change the default behaviour (so no new configuration should be necessary).

Boldly go where no one has gone before... :rocket:

**Comment by florianschanda** [comment]
@niklasnylen perhaps you could also check if this new approach is what you desired?

**Comment by niklasnylen** [comment]
@florianschanda yes, this is great, thank you!

**Comment by Remi-Gau** [comment]
Finally tool 5 minutes to check.

The only thing that throws an error is this.

```matlab
function initCppSpm()
  % (C) Copyright 2021 CPP BIDS SPM-pipeline developers
  %

```

```bash
mh_style initCppSpm.m 
In initCppSpm.m, line 1
| function initCppSpm()
|          ^^^^^^^^^^ style: Could not find any copyright notice
initCppSpm.m:5: style: more than one consecutive blank line
MISS_HIT Style Summary: 1 file(s) analysed, 2 style issue(s)
```

**Comment by florianschanda** [comment]
> Finally tool 5 minutes to check.
> 
> The only thing that throws an error is this.
> 
> ```matlab
> function initCppSpm()
>   % (C) Copyright 2021 CPP BIDS SPM-pipeline developers
>   %
> ```

OK, weird. I can reproduce this. Thanks for this.

Btw, I am holding off doing an official release with this fixed until I can also fix/rewrite the mh_copyright tool; as it needs major rework following this docstring support.

**Comment by florianschanda** [comment]
@Remi-Gau I fixed this problem on the `master` branch. Turns out the first line of each docstring was ignored. Oops :/

**Comment by florianschanda** [comment]
Right, I think this everything should be working now, and the MH Copyright tool now also correctly deals with docstrings.

I will release `0.9.18` with all this, once I get back to work next week. I still want to do a sanity check on my work's code base, just to make sure I have not missed anything obscure.
