### ISSUE TITLE
autofix indentation

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#14]
Related keywords should have the same indentation as the line starting the code body. Mostly this is relevant for the `end` keyword but `elseif` and `else` should also be aligned with their matching `if`.
Example of desired syntax:
```
function u = fcn(x)
    z = x + 3;
    if z > 7
        y = 'a';
    else
        y = 'b';
    end

    switch y
        case 'a'
            u = true;
        case 'b'
             u = false;
    end
end
```

**Comment by florianschanda** [comment]
I am increasing the scope of this issue to support auto-fixing all indentation.
