### ISSUE TITLE
Line continuation starting statements

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#142]
Using line continuation between properties leads to a messed up, albeit technically not erroneous, autofix.
Before:
```
properties
    foo, ...
    bar
end
```
After:
```
properties
    foo
    ...
    bar
end
```

Normal line continuation, such as the one below, does not give any strange behaviour in the properties section
```
properties
    foo = ...
        'bar'
end
```

**Comment by florianschanda** [comment]
@niklasnylen Just to let you know why this is still open: there are some situations where a single run with `--fix` leaves you in a state where you need to run `--fix` again. This process does terminate eventually, but it would be *really* good if only a single `--fix` run was necessary.

**Comment by florianschanda** [comment]
I am closing this now, and the multiple-fix problem will be resolved with the future tool `mh_reformat`
