### ISSUE TITLE
DOI minting on zenodo

### ISSUE THREAD

**Issue by Remi-Gau** [florianschanda/miss_hit#153]
**What kind of feature is this?**
use zenodo to get a citable DOI and certified long term storage of your code (in case github disappears or if microsoft decides to make us pay for it). 

See for example: https://zenodo.org/record/3556173

**MISS_HIT component affected**
none

**Describe the solution you'd like**
Synching zenodo to a github repo is actually pretty easy and everything is automated after that (the creation of a new release on github will create a new back up on zenodo with its own DOI)

https://guides.github.com/activities/citable-code/

**Comment by florianschanda** [comment]
Seems like a good idea; since a release is needed to trigger this I will include it in the next one.

**Comment by florianschanda** [comment]
I will incorporate this into my release process. Here is the first example:

https://doi.org/10.5281/zenodo.3967057
