### ISSUE TITLE
New rule: No use of true, false, pi etc as variable names

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#16]
In Matlab, some keyword-like words can be used without prior assignment or definition, but they can also be assigned a value. The most obvious ones are `true`, `false`, `pi`, `exp` and `eps` (technically `pi`, `exp` and `eps` are built-in functions but they have such specific meanings that there is no reasonable use case where assignment to them is necessary). Assigning something to these keywords can introduce severe, hard-to-find bugs.
Example
```
false = 0.01;
if false % Will evaluate to true since false has been assigned
    % Do something
end
```
A rule should be introduced to prevent assignment to certain variable names with `=`.

**Comment by florianschanda** [comment]
It's not trivial to do something better than the absolute simplest thing.
Consider
```
for i = [1, 2]   % is this bad?
```
Also, right now I have bugs. Consider
```
foo (pi > value) = 12;   % not a redefinition of pi
```
