### ISSUE TITLE
complain about statements in Contents.m

### ISSUE THREAD

**Issue by florianschanda** [florianschanda/miss_hit#203]
Files named `Contents.m` have special significance to the MATLAB help system. https://uk.mathworks.com/help/matlab/matlab_prog/create-a-help-summary-contents-m.html

MH Lint should ensure they contain nothing but comments.

**Comment by Remi-Gau** [comment]
Curious about one thing: `Contents.m` should be flagged as non conforming to the regex I have set up for function names.

Not sure I understand why it is is skipped?

**Comment by florianschanda** [comment]
If you don't have a function in your file, then MISS_HIT won't complain. Right now function naming is only checked for function declarations; but script files will be ignored. There should be two things happening, really:
* there should be _another_ regex (for mh style) you can configure for script names
* there should be a check (in mh lint) that makes sure function/class names match the filename

**Comment by florianschanda** [comment]
I have created #205 and #206 for these.

**Comment by florianschanda** [comment]
So there already was an existing check that the class or function name has to match the filename. However I repurposed #206 that any filename shouldn't shadow a built-in, like `true`. There was an existing check for this to stop you doing `false = 1;` but I missed checking filenames.
