### ISSUE TITLE
GitLab/GitHub links support in generated HTML

### ISSUE THREAD

**Issue by alvinseville7cf** [florianschanda/miss_hit#204]
**What kind of feature is this?**
* New feature in MISS_HIT

**MISS_HIT component affected**
Choose one or more of the below:
* Style checker

**Describe the solution you'd like**
Now the following command:
```bash
mh_style --html report file_name.m
```
produces smth like this:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="file:../../../../../../../../home/Alvin/.local/bin/docs/style.css">
<title>MISS_HIT Report</title>
</head>
<body>
<header>MISS_HIT Report</header>
<main>
<div></div>
<h1>Issues identified</h1>
<section>
<h2>Secant method.m</h2>
<div class="message"><a href="matlab:opentoline('Secant method.m', 1)">Secant method.m: line 1:</a> lex error: unexpected character &#x27;#&#x27;</div>
<div class="message"><a href="matlab:opentoline('Secant method.m', 1, 81)">Secant method.m: line 1:</a> style: line exceeds 80 characters</div>
</section>
</main>
</body>
</html>
```
But what if I want to use it in my CI in GitLab/GitHub? Maybe it is a good idea to add `--gitlab-ci` and `--github-ci` options to refer to code string in GitLab/GitHub repo.

**Comment by florianschanda** [comment]
You mean instead of the `matlab:opentoline` stuff? Can you please give me an example of what you'd like instead?

**Comment by florianschanda** [comment]
Or, would you like MISS_HIT to use the GitHub/GitLab API to post review comments on your code?

**Comment by alvinseville7cf** [comment]
> You mean instead of the `matlab:opentoline` stuff? Can you please give me an example of what you'd like instead?

Yes. Example: [`https://gitlab.com/dvfu-university/calculus/testci/-/blob/master/main.m#L15`](https://gitlab.com/dvfu-university/calculus/testci/-/blob/master/main.m#L15).

**Comment by florianschanda** [comment]
I see a few issues with this, maybe you have a good idea on resolving this:
* I do not see how I can derive the above root URL from the code. I could possibly do this _if_ I look into the `.git` directory, but so far I have tried my very best to keep MISS_HIT version control agnostic. Yes, everyone should really be using git, but there are a bunch of engineering companies where Git (or even SVN) hasn't quite... arrived yet.
* Even if I do this, then the link would point to some online version, which may or may not match the actual files analysed if you have local changes. This would be a source of confusion.

**Comment by florianschanda** [comment]
@alvinseville7cf since I didn't hear anything here for 2 weeks I am closing this ticket. Please re-open if you have an idea specifically for my second question.

**Comment by florianschanda** [comment]
@alvinseville7cf since I didn't hear anything here for 2 weeks I am closing this ticket. Please re-open if you have an idea specifically for my second question.
