### ISSUE TITLE
Copyright should also be allowed for the format which is recognized by Octave's get_help_text

### ISSUE THREAD

**Issue by quazgar** [florianschanda/miss_hit#220]
## What kind of feature is this?

* Support `Copyright (C)` in addition to `(C) Copyright`.
* This improves the interoperability with [Octave's `get_help_text()` function](https://octave.org/doc/interpreter/Getting-Help.html#XREFget_005fhelp_005ftext).

## MISS_HIT component affected
* Style checker: copyright

## Describe the solution you'd like

Currently, miss_hit only recognizes `(C) Copyright` as the beginning of a copyright notice.  Unfortunately, this is not recognized by Octave's `get_help_text()` function, and so the sometimes pretty verbose copyright text ends up in the help text and possibly HTML documentation. `get_help_text()` does however recognize the string `Copyright (C)` and will omit such a comment paragraph.

Teaching miss_hit to also accept `Copyright (C)` would make both sides happy.

## How I can help

I am willing to help with rewriting the `copyright_notice` regex, but I do not know if there are unintended side effects for the automatic copyright notice tools.

**Comment by florianschanda** [comment]
Great suggestion. I really should do more in the area of Octave support.

**Comment by florianschanda** [comment]
@quazgar I have fixed this. Sorry I could not use your PR, but as you identified here already there was work required in the `mh_copyright` tool.

I have updated the default regex to accept either `(c) Copyright...` or `Copyright (c)...` (but not `(c) Copyright (c)`). You can also use capitals. The mh_copyright tool now also does the right thing (by copying the existing style, and giving you a way to specify what you want in case there is no notice at all).
