### ISSUE TITLE
"Tag" itself from pragmas is reported in mh_trace

### ISSUE THREAD

**Issue by BrunoSalami** [florianschanda/miss_hit#229]
**MISS_HIT Component affected**
Please choose one from:
* mh_trace / m_ast

**Your MATLAB/Octave environment**
* MATLAB R2017b

**Your operating system and Python version**
* Linux, python3

**Describe the bug**
when using pagma "Tag"
```
%| pragma Tag("Tag", "req-pc-count-em-nicely");
```
"Tag" also appears in the json report
```
{
    "suite::test": {
        "shared": false,
        "source": {...},
        "tags": [
            "Tag",
            "req-pc-count-em-nicely"],
        "test": false
    }
}
```

**Comment by florianschanda** [comment]
This is working as intended. You list two tags, `Tag` and `req-pc-count-em-nicely`, and both appear as requested ;)
Did you mean to write:
```
%| pragma Tag("req-pc-count-em-nicely");
```
