### ISSUE TITLE
Update --help output

### ISSUE THREAD

**Issue by EmilySeville7cfg** [florianschanda/miss_hit#244]
**What kind of feature is this?**
* New feature in MISS_HIT

**MISS_HIT component affected**
Choose one or more of the below:
* Style checker
* Code metrics
* Documentation

**Describe the solution you'd like**

Update all help according to [Microsoft command-line syntax](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key).

**Comment by florianschanda** [comment]
Sorry, I will have to reject this ticket. The command-line help text is formatted using python argparse; and is generally unixy and I will not change it; as I think it would involve replacing or re-writing significant parts of argparse.

Please see https://docs.python.org/3/library/argparse.html

Unless I mis-understood this ticket and you're talking about a more specific change (which I would be happy to discuss in isolation).
