### ISSUE TITLE
Copyright statement in the second top-level comment block 

### ISSUE THREAD

**Issue by drittelhacker** [florianschanda/miss_hit#259]
**What kind of feature is this?**
* Support for slightly more flexible placement of copyright statements

**Your MATLAB/Octave environment**
* both MATLAB and Octave
* any release

**MISS_HIT component affected**
Choose one or more of the below:
* Style checker
* Copyright updater

**Describe the solution you'd like**
In our projects, we usually have something like:
```
function [outputArg1,outputArg2] = untitled(inputArg1,inputArg2)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

%
% This file is part of the foo project 
% (http://my.url.to/project/foo).
% Copyright (c) 2022 foo developers and contributors.
% All rights reserved.
% License: BSD 2-Clause License (see COPYING)
%

outputArg1 = inputArg1;
outputArg2 = inputArg2;
end
```
This way, we do not print the license statement every time users check for the help, but still comply to the license-at-the-top rules in open source software. Removing the empty line between the two comments makes the copyright tool and style checker find the copyright statement already. It would be great if both would also support this style, with the extra blank line.

**Comment by florianschanda** [comment]
First, sorry in the month long delay.

Second, this sounds like something I could do fairly easily.

**Comment by drittelhacker** [comment]
Sounds great. Take your time. This would be really nice to have, but is also not urgent at all.

**Comment by florianschanda** [comment]
This is now implement and will be in the next release (which I will make today).

**Comment by drittelhacker** [comment]
Many thanks! I just tested the copyright detection of `mh_style` on one of our projects with almost 400 m-files, and it worked flawlessly. Nice work.
