### ISSUE TITLE
The command `mh_style` han't been added in path

### ISSUE THREAD

**Issue by zousiyu1995** [florianschanda/miss_hit#262]
Python: miniconda3

In the QUICK START section on website of `https://misshit.org/`, two commands are given.

When I run the command,

```shell
pip3 install miss_hit
```
It will add three commands, namely `mh_copyright.exe`, `mh_diff`, `mh_lint`, into the path `~/miniconda3/Script`. But, there is no `mh_style`. So, I can't run the command as follows,

```shell
mh_style --fix my_program.m
```

**Comment by florianschanda** [comment]
This ticket prompted me to review the setup files; and `mh_trace` was actually missing, which I have fixed in https://github.com/florianschanda/miss_hit/commit/50299f74867cecfd89bc0c922c8fd8071c7b42a1
