### ISSUE TITLE
[BUG] config with file length  > 1000 is ignored

### ISSUE THREAD

**Issue by Remi-Gau** [florianschanda/miss_hit#263]
**MISS_HIT Component affected**

* Style checker: 
* MISS_HIT 0.9.36

**Your MATLAB/Octave environment**

* MATLAB 2017a

**Your operating system and Python version**

* Linux Ubuntu 22.04
* Python 3.9.13

**Describe the bug**

mh_style will throw the following:

```bash
Model.m:1012: style: file exceeds 1000 lines [file_length]
```

despite my config looking like this:

```text
project_root

copyright_entity: "Remi Gau"

metric "file_length": limit 1500
```

Tried to replicate this in the most bare bone project that looks like this:

```
.
├── miss_hit.cfg
└── Model.m
```

**Comment by florianschanda** [comment]
This is an annoying old behaviour. There are two independent kinds of checks that check for file length:
* mh_metric (which is what you configured)
* mh_style (which you probably should turn off, check `file_length`)

**Comment by Remi-Gau** [comment]
was not aware of those 2 options.

thanks
