### ISSUE TITLE
Recommend install with pipx

### ISSUE THREAD

**Issue by jamesmyatt** [florianschanda/miss_hit#269]
If you're only using it as a CLI tool, then I'd recommend installing this tool in an isolated environment using pipx (or at least providing the instructions for it). The relevant command (once pipx is installed) is:

```
pipx install miss_hit --include-deps
```

[pipx](https://pypa.github.io/pipx/) is the PyPA recommended approach for standalone tools.

Sorry, I don't have time for a PR.

**Comment by florianschanda** [comment]
No worries. I'll add these as alternative instructions.
