### ISSUE TITLE
Provide a console script entry point for mh_style

### ISSUE THREAD

**Issue by ThomasFeher** [florianschanda/miss_hit#281]
**What kind of feature is this?**
* New feature in MISS_HIT

**Your MATLAB/Octave environment** (not really relevant)
* Octave
* v8.3.0

**MISS_HIT component affected**
* Style checker

**Describe the solution you'd like**
`mh_style` should supply a console script entry point as described [here](https://github.com/pypa/pipx#where-does-pipx-install-apps-from) in order to support installation via `pipx`. Other components of miss_hit, like `mh_lint`, do so already.

**Comment by florianschanda** [comment]
I also downloaded the latest published miss_hit_core wheel file, and looked into entry_points.txt:

```
[console_scripts]
mh_metric = miss_hit_core.mh_metric:main
mh_style = miss_hit_core.mh_style:main
```

So sounds perhaps like a pipx bug? Either way, MH is doing everything correctly as far as I can tell.

**Comment by florianschanda** [comment]
I also did a test install in a clean environment (with `pip`) and the script `mh_style` is created.

**Comment by ThomasFeher** [comment]
Maybe this is really an issue with `pipx`. I tried now installing `miss_hit_core` explicitly (while having installed `miss_hit` already) and this added `mh_style` and `mh_metric`.

So for anyone having the same issue. The correct way seems to be:

```
pipx install miss_hit_core
pipx install miss_hit
```

**Comment by florianschanda** [comment]
Sounds like `pipx` is not respecting dependencies...? I have created an issue with them.

**Comment by ThomasFeher** [comment]
Thank you. The issue [they are referring to](https://github.com/pypa/pipx/issues/1024) suggests using `--include-deps`, which works for me, as well.

So the better solution ist to:

```
pipx install --include-deps miss_hit
```
