### ISSUE TITLE
Does it support calls in Python code?

### ISSUE THREAD

**Issue by 17Reset** [florianschanda/miss_hit#285]

**Comment by florianschanda** [comment]
I do not understand this ticket. Can you please elaborate on the question?

**Comment by 17Reset** [comment]
Called as an API in Python code, not cli mode

**Comment by florianschanda** [comment]
Of course. Please have a look at https://github.com/florianschanda/miss_hit/blob/master/miss_hit_core/mh_metric.py#L1166 how to create a new backend.

You can also directly instantiate a parser but it's a bit more tricky. You can have a look at https://github.com/florianschanda/miss_hit/blob/master/miss_hit_core/command_line.py#L262 what is necessary.

You can skip all the config mechanism, and just create an instance of MATLAB_Parser (see https://github.com/florianschanda/miss_hit/blob/master/miss_hit_core/m_parser.py#L89)

The smallest example of this is the debug script: https://github.com/florianschanda/miss_hit/blob/master/mh_debug_parser

HTH
