### ISSUE TITLE
Method naming applied to setters and getters leads to false positives

### ISSUE THREAD

**Issue by pvogt09** [florianschanda/miss_hit#287]
**MISS_HIT Component affected**
Please choose one from:
* Style checker

**Your MATLAB/Octave environment**
* MATLAB
* R2023B

**Your operating system and Python version**
* Linux
* python 3.8.10

**Describe the bug**
Running the style checker on
```
classdef Setter < handle
    properties (SetAccess = private)
        Attribute
    end

    methods

        function set.Attribute(this, attribute)
            this.Attribute = attribute;
        end

    end
end
```
results in a style violation
```
In Setter.m, line 8
|        function set.Attribute(this, attribute)
|                      ^^^^^^^^^^style: violates naming scheme for method [naming_functions]
```
being reported when using a default settings that should not be reported because there are no style restrictions on attributes imposed.
`set.*` and `get.*` methods have to contain the name of the attribute to work at all, so they should be treated differently compared to normal methods. Maybe a special naming scheme parameter for class attributes could be introduced to take this into account or the part after the dot could be checked against the names of the attributes the class has (although this might not work well with inheritance in case the parent class is not available).

**Comment by florianschanda** [comment]
Originally I thought this would be impossible to do but maybe not. I'll see what I can do. I assume setters and getters are matlab constructs and they have special meaning?

**Comment by pvogt09** [comment]
They are just like normal methods with the exception that they start with `set.` and `get.` which is an illegal name for any other type of function or method and the "function name" is the name of the property they set or get. They are documented [here](https://de.mathworks.com/help/matlab/matlab_oop/property-set-methods.html).

**Comment by florianschanda** [comment]
I have implemented this and pushed a new release. Let me know if there are problems.

**Comment by pvogt09** [comment]
No, it works fine and by allowing every naming convention for class attributes, I was able to make the codebase pass the style check. Thanks for fixing this so quickly.
