### ISSUE TITLE
proceed mh_trace on missing exclude_dir folders

### ISSUE THREAD

**Issue by gabeTaucher** [florianschanda/miss_hit#292]
**MISS_HIT Component affected**
Please choose one from:
* mh_trace

**Your MATLAB/Octave environment**
* MATLAB R2021b Update 4

**Your operating system and Python version**
* Windows
* python 3.12.1

**Describe the bug**
I execute "mh_trace" and use "exclude_dir:" functionality in "miss_hit.cfg". If a folder specified in "exclude_dir:" doesn't exist in this location "mh_trace" reports an error and doesn't generate the tracing artifacts. 
This gets relevant, since I want to exclude generated directories from traceability analysis, which are not present in an all new instance of the repo, but might get generated at some time during development.

Since the directory shouldn't be included in traceability anyway a warning should be sufficient and generation of tracing artifacts should proceeded.

**Comment by Remi-Gau** [comment]
Seems related to this.

https://github.com/florianschanda/miss_hit/issues/234

**Comment by florianschanda** [comment]
I found a way to fix this that wasn't a total rewrite of the config system. Will be in the next release :)

**Comment by gabeTaucher** [comment]
Great. Thank you @florianschanda!
