### ISSUE TITLE
No naming rules for variables?

### ISSUE THREAD

**Issue by rnwst** [florianschanda/miss_hit#293]
I had a look at the [documentation on configuration](https://florianschanda.github.io/miss_hit/style_checker.html) and I can't find a configuration option for naming variables. There is a naming rule for function parameters (`naming_parameters`), but this does not apply to variables that are not function parameters. Apologies if I'm missing something obvious here!

**Comment by florianschanda** [comment]
That's unfortunately correct and can't easily be implemented since it requires semantic analysis to figure out what the variables are.

MISS_HIT does not have a semantic analysis done yet.

**Comment by rnwst** [comment]
Thanks for the explanation. I should mention that `miss_hit` is an awesome project, and I wouldn't know what to do without it! Thanks a lot for all your hard work!

**Comment by florianschanda** [comment]
Thank you so much! That means a lot and glad I could help out!
