### ISSUE TITLE
How to get the AST in the same program, without calling `command_line.execute`

### ISSUE THREAD

**Issue by h-mole** [florianschanda/miss_hit#295]
Thanks for this work, really helped me a lot. But when I was trying to get the AST of MATLAB,  I got stuck because I have to call this tool in subprocess. Is there any way to get the AST in the same program, without calling `command_line.execute`?  And if it is possible in the current version, could you please provide me a code snippet for the solution?

Thanks!

**Comment by hzyrc6011** [comment]
This code snippet worked for me, but is there any more simple way for this? Thanks!

```
def main_handler(code: str):
    filename = os.path.join(os.path.dirname(__file__), "_placeholder.m")
    options = Namespace(
        version=False,
        octave=None,
        matlab=None,
        include_version=False,
        files=[filename],
        entry_point=None,
        single=False,
        ignore_config=False,
        input_encoding="utf8",
        ignore_pragmas=False,
        ignore_justifications_with_tickets=False,
        brief=False,
        debug_show_path=False,
        language=None,
    )

    mh = Message_Handler("debug")

    mh.show_context = not options.brief
    mh.show_style = False
    mh.show_checks = True
    mh.autofix = False
    options.single = True

    mh.register_file(filename)
    cfg_tree.register_item(mh, pathutil.abspath("."), options)

    cfg_tree.validate_project_config(mh)
    cfg = cfg_tree.get_config(filename)
    lexer = MATLAB_Lexer(
        MATLAB_2017b_Language(),
        mh,
        code,
        filename,
        None,
    )
    parser = MATLAB_Parser(mh, lexer, cfg)
    n_cu = parser.parse_file()
    visitor = MyVisitor()
    n_cu.visit(
        None,
        visitor,
        "Root",
    )
    return visitor.generated_code
```

**Comment by florianschanda** [comment]
So there is a lot going on that the main handler does, but you can skip it if you wish.

You can use this as inspiration: https://github.com/florianschanda/miss_hit/blob/master/mh_debug_parser

**Comment by florianschanda** [comment]
The important parts you need to do are:
* create a messagehandler https://github.com/florianschanda/miss_hit/blob/master/mh_debug_parser#L121
* register the file https://github.com/florianschanda/miss_hit/blob/master/mh_debug_parser#L55
* create lexer, parser, and config object https://github.com/florianschanda/miss_hit/blob/master/mh_debug_parser#L63-L67
* call parse_file
