### ISSUE TITLE
Autofix of trailing whitespaces after "..." not working

### ISSUE THREAD

**Issue by niklasnylen** [florianschanda/miss_hit#83]
Trailing whitespaces after a line continuation (...) are not removed when the --fix argument is set.
Example (underscore represents whitespace):
```
function testfile()_
x = y + ...___
 z;__
```
is auto corrected to
```
function testfile()
x = y + ...___
 z;
```

**Comment by florianschanda** [comment]
This is now fixed. Thanks for the report :)
